### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [marcusmohr/qgs-gazetteer-bb#1]
# Problem

Can you please change the plugin homepage link in metadata.txt to link to this repo rather than your github profile

**Comment by marcusmohr** [comment]
I changed it (https://github.com/marcusmohr/qgs-gazetteer-bb/commit/70f0d38cd6e22bdcbb89eda17dbc3cdf172a7ca0) and uploaded it again to the QGIS Python Plugins Repository.
